"""collections table

Revision ID: 04e83c756c65
Revises: 89341456cf89
Create Date: 2026-10-08 18:14:23.711749

"""
from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401  the Vector type used by the chunks table
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04e83c756c65'
down_revision: Union[str, Sequence[str], None] = '89341456cf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
