"""6A saved citations, user role label, app profiles

Revision ID: 89341456cf89
Revises: 865d353c9fd9
Create Date: 2026-10-08 10:20:09.438249

"""
from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401  the Vector type used by the chunks table
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '89341456cf89'
down_revision: Union[str, Sequence[str], None] = '865d353c9fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_profiles',
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.add_column('messages', sa.Column('citations', sa.JSON(), nullable=True))
    op.add_column('request_logs', sa.Column('user_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'user_role')
    op.drop_column('messages', 'citations')
    op.drop_table('app_profiles')
    # ### end Alembic commands ###
